RNTrack_kotlinVersion=1.8.0
RNTrack_minSdkVersion=23
RNTrack_targetSdkVersion=34
RNTrack_compileSdkVersion=34
RNTrack_ndkversion=26.1.10909125
RNTrack_buildToolsVersion=34.0.0
RNTrack_media3Version=1.4.1
RNTrack_useExoplayerIMA=false
RNTrack_useExoplayerRtsp=false
RNTrack_useExoplayerSmoothStreaming=true
RNTrack_useExoplayerDash=true
RNTrack_useExoplayerHls=true
RNTrack_androidxCoreVersion=1.13.1
RNTrack_androidxActivityVersion=1.8.2
RNTrack_buildFromMedia3Source=false
